name: Movie List CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8082'
